# Generated by Django 2.2.6 on 2019-10-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('acc_type', models.CharField(choices=[('CA', 'Current Account'), ('SA', 'Savings Account'), ('RD', 'Reccuring Deposit'), ('FD', 'Fixed Deposit'), ('ZB', 'Zero Balance')], max_length=2, primary_key=True, serialize=False)),
                ('minbal_type', models.IntegerField(choices=[(0, 'CA_min'), (1, 'SA_min'), (2, 'RD_min'), (3, 'FD_min'), (4, 'ZB_min')], unique=True)),
                ('roi_type', models.DecimalField(choices=[(0, 'CA_roi'), (1, 'SA_roi'), (2, 'RD_roi'), (3, 'FD_roi'), (4, 'ZB_roi')], decimal_places=2, max_digits=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('br_abbr', models.CharField(max_length=3, unique=True)),
                ('br_addr', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('br_email', models.EmailField(max_length=254)),
                ('br_phone', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_no', models.AutoField(primary_key=True, serialize=False)),
                ('acc_balance', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AccountType')),
                ('mother_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Branch')),
            ],
        ),
    ]
