# Generated by Django 2.2.6 on 2019-10-08 05:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='br_city',
            field=models.CharField(default='mumbai', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_installments', models.IntegerField()),
                ('amount_paid', models.BigIntegerField()),
                ('installments_paid', models.IntegerField()),
                ('loan_cleared', models.BooleanField(default=False)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('u_phone', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('atm_id', models.AutoField(primary_key=True, serialize=False)),
                ('atm_city', models.CharField(max_length=50)),
                ('atm_addr', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(default=1111111111, on_delete=django.db.models.deletion.CASCADE, to='main.BankUser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_no', models.IntegerField()),
                ('card_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('valid_from', models.DateField(default=datetime.datetime.now)),
                ('valid_thru', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
            ],
            options={
                'unique_together': {('card_type', 'acc_no')},
            },
        ),
    ]
