# Generated by Django 2.2.6 on 2019-10-08 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191008_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 10, 8, 17, 55, 36, 882694))),
                ('paid_from', models.CharField(max_length=11)),
                ('paid_to', models.CharField(max_length=11)),
                ('amount', models.BigIntegerField()),
                ('about_txn', models.TextField()),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
            ],
        ),
    ]
