# Generated by Django 2.2.6 on 2019-10-08 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='acc_no',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 20, 8, 37, 268802)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_from', to='main.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to', to='main.Account'),
        ),
    ]
