# Generated by Django 2.2.6 on 2019-10-18 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191008_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='credit_score',
            field=models.IntegerField(default=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 3, 41, 22, 950251)),
        ),
    ]
